blueprint:
  name: BookSwapModernUI2025
  description: |
    UI design strategy and style guide for a modern book sharing website.
    Focused on clean, personalized, accessible experience with vibrant modern aesthetics.
  author: BookSwap_Design_Team
  version: 2.0

  designPhilosophy:
    - userCentered: true
    - aiDrivenPersonalization: true
    - clarityAndSimplicity: true
    - accessibilityCompliance: WCAG_2.1
    - modernVibrantAesthetic: true

  colors:
    primary:
      - name: Indigo
        hex: "#6366f1"
        usage: "Primary actions, CTAs, active states"
      - name: Indigo Hover
        hex: "#4f46e5"
        usage: "Hover states"
      - name: Indigo Dark
        hex: "#4338ca"
        usage: "Active/pressed states"
    secondary:
      - name: Purple
        hex: "#8b5cf6"
        usage: "Secondary actions, wishlist features"
    accent:
      - name: Pink
        hex: "#ec4899"
        usage: "Accent highlights, special features"
    semantic:
      - name: Success Green
        hex: "#10b981"
        usage: "Success states, available items"
      - name: Warning Amber
        hex: "#f59e0b"
        usage: "Warnings, wanted items"
      - name: Danger Red
        hex: "#ef4444"
        usage: "Errors, destructive actions"
      - name: Info Blue
        hex: "#3b82f6"
        usage: "Information, neutral highlights"
    darkTheme:
      backgrounds:
        - name: Primary Background
          hex: "#0f172a"
          usage: "Main page background"
        - name: Secondary Background
          hex: "#1e293b"
          usage: "Cards, elevated surfaces"
        - name: Tertiary Background
          hex: "#334155"
          usage: "Hover states, input backgrounds"
        - name: Elevated Background
          hex: "#475569"
          usage: "Borders, dividers"
      text:
        - name: Primary Text
          hex: "#f1f5f9"
          usage: "Main text content"
        - name: Secondary Text
          hex: "#cbd5e1"
          usage: "Subtitles, descriptions"
        - name: Muted Text
          hex: "#94a3b8"
          usage: "Placeholder, disabled text"

  spacing:
    scale:
      - xs: "0.25rem"    # 4px - tight spacing
      - sm: "0.5rem"     # 8px - default small
      - md: "1rem"       # 16px - default medium
      - lg: "1.5rem"     # 24px - section spacing
      - xl: "2rem"       # 32px - large spacing
      - "2xl": "3rem"    # 48px - hero spacing

  borderRadius:
    scale:
      - sm: "0.375rem"   # 6px
      - md: "0.5rem"     # 8px
      - lg: "0.75rem"    # 12px
      - xl: "1rem"       # 16px

  shadows:
    levels:
      - sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)"
      - md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)"
      - lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)"
      - xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)"

  transitions:
    durations:
      - fast: "150ms cubic-bezier(0.4, 0, 0.2, 1)"
      - base: "250ms cubic-bezier(0.4, 0, 0.2, 1)"
      - slow: "350ms cubic-bezier(0.4, 0, 0.2, 1)"

  styles:
    - modernCards:
        description: "Elevated cards with rounded corners, subtle shadows, and hover effects"
        features: ["transform on hover", "smooth transitions", "gradient backgrounds"]
    - darkMode:
        primary: true
        background: "#0f172a"
        text: "#f1f5f9"
        accentColors:
          - "#6366f1"  # Indigo
          - "#8b5cf6"  # Purple
          - "#ec4899"  # Pink
    - typography:
        fontFamily: "system-ui, -apple-system, sans-serif"
        weights: ["400", "500", "600", "700"]
        scale:
          - display: "36px/40px - Hero headlines"
          - h1: "30px/36px - Page titles"
          - h2: "24px/32px - Section headers"
          - h3: "20px/28px - Card titles"
          - body: "16px/24px - Default text"
          - small: "14px/20px - Secondary text"
          - tiny: "12px/16px - Captions"
        characteristics: "Clean, modern, highly legible with gradient text support"
    - microInteractions:
        enabled: true
        examples:
          - "Button lift on hover with scale transform"
          - "Image zoom on card hover"
          - "Smooth color transitions"
          - "Gradient text effects on headers"
    - responsiveDesign:
        approach: "Mobile-first with CSS Grid"
        breakpoints:
          - mobile: "< 480px - 2 columns"
          - tablet: "768px - 4 columns"
          - desktop: "1024px - 6 columns"
        features: ["auto-fill grid", "flexible layouts", "touch-friendly 44px+ targets"]

  keyUIComponents:
    pageHeaders:
      - component: "page-header"
        features:
          - gradientBackground: true
          - centeredText: true
          - leadDescription: true
          - borderRadius: "xl"
          - actionButtons: "integrated in header"
    bookCards:
      - component: "book-card"
        features:
          - gridLayout: "auto-fill minmax(160px, 1fr)"
          - imageZoomOnHover: true
          - statusBadges: ["copies available", "wanted count"]
          - transformOnHover: "translateY(-4px)"
          - shadows: "xl on hover"
    navigation:
      - component: "bookswap-nav"
        features:
          - threeColumnGrid: true
          - searchBar: "center column"
          - hoverStates: "background highlight"
          - activeIndicators: true
    buttons:
      - primary: "Indigo background, white text, hover lift"
      - secondary: "Purple background for wishlist actions"
      - danger: "Red background for destructive actions"
      - states: ["default", "hover", "active", "disabled"]

  implementedFeatures:
    - customCSSDesignSystem: "static/css/bookswap.css with CSS variables"
    - crispyForms: "Bootstrap 5 form styling with django-crispy-forms"
    - dualActionButtons: "Library + Wishlist toggle on book pages"
    - consistentPageHeaders: "All pages use page-header class"
    - responsiveGrid: "Book cards adapt to screen size"
    - hoverAnimations: "Smooth transforms and color transitions"

  developmentBestPractices:
    - designSystem: "CSS custom properties for consistency"
    - componentReuse: "Reusable classes across templates"
    - mobileFirst: "Responsive breakpoints in CSS"
    - accessibilityFirst: "WCAG 2.1 compliant colors and interactions"
    - djangoIntegration: "Template-based with crispy-forms"

