# Generated by Django 5.0.1 on 2024-02-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description_html",
            field=models.TextField(blank=True, default="", editable=False),
        ),
    ]
