# Generated by Django 5.0.1 on 2024-01-29 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ManyToManyField(through='books.UserBook', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='returned_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
