# Generated by Django 5.0.1 on 2024-02-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_authors_book_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pagecount",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
