# Generated by Django 5.0.1 on 2025-10-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_description_alter_book_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='cancelled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
