# Generated by Django 5.0.1 on 2025-10-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_requestbook_cancelled_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='info_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='maturity_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='ratings_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
