# Generated by Django 5.0.1 on 2024-02-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="decision",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
