# Generated by Django 5.0.1 on 2024-02-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="removed_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
