# Generated by Django 5.0.1 on 2024-02-06 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_wishlist_removed_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="description_html",
        ),
        migrations.AddField(
            model_name="group",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userbook",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_owners",
                to="books.book",
            ),
        ),
    ]
