# Generated by Django 5.0.1 on 2025-10-24 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_add_google_books_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
