# Generated by Django 5.0.1 on 2024-02-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_remove_group_description_html_group_is_private_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
