# Generated by Django 5.0.1 on 2024-02-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_rename_request_requestbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestbook",
            name="reject_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Book no longer owned", "Book no longer owned"),
                    ("Book already loaned", "Book already loaned"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
